// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBMNgAMcy0TVMr4VNnq_08DxYC7c1PfN0',
    appId: '1:890102022489:web:2937ddd0fcdcc6f84d8c48',
    messagingSenderId: '890102022489',
    projectId: 'testesp8266-1427e',
    authDomain: 'testesp8266-1427e.firebaseapp.com',
    databaseURL: 'https://testesp8266-1427e-default-rtdb.firebaseio.com',
    storageBucket: 'testesp8266-1427e.firebasestorage.app',
    measurementId: 'G-4V1VR2GYZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcqLzv93UsPcqRe3iKrm-mmxnKWPQYbIk',
    appId: '1:890102022489:android:8592c84a7cfea35f4d8c48',
    messagingSenderId: '890102022489',
    projectId: 'testesp8266-1427e',
    databaseURL: 'https://testesp8266-1427e-default-rtdb.firebaseio.com',
    storageBucket: 'testesp8266-1427e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb1DM0TiY6n0TmY14he1QHvN3fm_Zv2Gk',
    appId: '1:890102022489:ios:ab33686fcc8a24374d8c48',
    messagingSenderId: '890102022489',
    projectId: 'testesp8266-1427e',
    databaseURL: 'https://testesp8266-1427e-default-rtdb.firebaseio.com',
    storageBucket: 'testesp8266-1427e.firebasestorage.app',
    androidClientId: '890102022489-qh2ge60t7ff2s6kroo14r920gcc6flka.apps.googleusercontent.com',
    iosClientId: '890102022489-0bgpbn4v9jugr7t0ciggo8qhmpj6m1nl.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb1DM0TiY6n0TmY14he1QHvN3fm_Zv2Gk',
    appId: '1:890102022489:ios:ab33686fcc8a24374d8c48',
    messagingSenderId: '890102022489',
    projectId: 'testesp8266-1427e',
    databaseURL: 'https://testesp8266-1427e-default-rtdb.firebaseio.com',
    storageBucket: 'testesp8266-1427e.firebasestorage.app',
    androidClientId: '890102022489-qh2ge60t7ff2s6kroo14r920gcc6flka.apps.googleusercontent.com',
    iosClientId: '890102022489-0bgpbn4v9jugr7t0ciggo8qhmpj6m1nl.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartHome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAPPs_IEkMUqZTd5-VXK1xG4e6KGr3yxg',
    appId: '1:890102022489:web:bf21a10a12b51c654d8c48',
    messagingSenderId: '890102022489',
    projectId: 'testesp8266-1427e',
    authDomain: 'testesp8266-1427e.firebaseapp.com',
    databaseURL: 'https://testesp8266-1427e-default-rtdb.firebaseio.com',
    storageBucket: 'testesp8266-1427e.firebasestorage.app',
    measurementId: 'G-3N2ZLH2X9C',
  );
}
